apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  DB_NAME: {{ .Values.config.database.name | quote }}
  DB_USER: {{ .Values.config.database.user | quote }}
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}