apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    {{- include "shopnest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.products.service.type }}

  selector:
    app: products

  ports:
    - name: http
      port: {{ .Values.products.service.port }}
      targetPort: {{ .Values.products.service.targetPort }}
      protocol: TCP