apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "shopnest.labels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    app: redis

  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
      protocol: TCP