import { Link } from 'react-router-dom'
import Hero from '../components/Hero'
import ProductCard from '../components/ProductCard'

function Home({ products }) {
  const featured = products.slice(0, 3)
  return <><Hero /><main><section className="section container" id="featured"><div className="section-heading"><div><p className="eyebrow">A few favorites</p><h2>Made to be lived with.</h2></div><Link className="text-link" to="/products">View all products <span>↗</span></Link></div><div className="featured-grid">{featured.map((product) => <ProductCard key={product.id} product={product} featured />)}</div></section><section className="category-band"><div className="container"><div className="section-heading"><div><p className="eyebrow">Browse by mood</p><h2>Find your next favorite.</h2></div></div><div className="category-grid"><Link to="/products?category=Home" className="category-tile home-tile"><span>Home objects</span><small>Quiet upgrades for your space ↗</small></Link><Link to="/products?category=Technology" className="category-tile tech-tile"><span>Modern tools</span><small>Thoughtful tech for better days ↗</small></Link><Link to="/products?category=Accessories" className="category-tile style-tile"><span>Personal style</span><small>Details that do the talking ↗</small></Link></div></div></section><section className="manifesto-section container"><div className="manifesto-number">02</div><div><p className="eyebrow">The ShopNest standard</p><h2>Less noise.<br /><em>More meaning.</em></h2></div><div className="manifesto-copy"><p>We look for the objects you reach for every day, then ask them to do a little more. Better materials, honest design, and a reason to keep them around.</p><Link className="text-link" to="/products">Discover our edit <span>↗</span></Link></div></section><section className="newsletter-section"><div className="container newsletter-inner"><div><p className="eyebrow">The good list</p><h2>Notes on living well.</h2><p>New arrivals, thoughtful finds, and a little inspiration. Once a month.</p></div><form className="newsletter-form" onSubmit={(event) => event.preventDefault()}><label htmlFor="email">Your email address</label><div><input id="email" type="email" placeholder="you@example.com" required /><button className="button button-dark" type="submit">Sign me up <span>↗</span></button></div></form></div></section></main></>
}

export default Home
